version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      PNr6RT765d6QgEmmYqOfcBEL7tGk3/YG1Hp+wPqtldkbwcSeqvkidj3N/gS6K/hpdtvN+PMHL+bPOwhQV6zrij1P5ptTap4O1QbHBWgV2YXWPzE+et5e7eWy/oU1dtToB3d/eE2YopN4aUrFxYBsx/5h9wCLsD16rCqWPBaPE1aelTpTOywvHWo0gMvwyP+KOz6awt1j5HYyZHH1R4I0SyeYkBSqnC7UBLn6dZdFmk+mvJ/r4SLkDeCFlegiOVdY0Ij9XNy1cKWWID3J+++jVEz5uIVubu1umAW1ZsaviVGyk4bgvQRjEI8R4uHq5JBOoW5gYyqXmLVJScY35r6xaut1KKIUv5yaXc4mMP720ADDMveVjowZLpIegvMehzyKWeLqNt3X04Aqn39NQHKBTqIfplQlUv6YdGuojNSD4oEpDKRTsJGU8uwqul2gc4+BGJ9vxqJY/nZzpNhmj3Ob/jnnSHZsdkmwoH9IfditloJzBtzK27Nym4Q8C5GN3uRmN8rsxi3eVMO2FmwKPcdWrm6BrfB5ah3FJ8+hAinsqgFUBn+F3wVdk4rqjiKIVDRskRgAZhQlytBJ3Xa91pcmmliawwPlU8JPUe/NU3mx9xOQ/uI6Z0lWhhVomiE7Cou8DL6PLPab+1cBOyB2SHI9UT4s1NhxRTb32eeQCS5buFk=
