version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      hex64tvldhCchxnxqMvGsHR2zX3mRgGkBCTW0vvJZQf6+EO7EYYbaDxJa+L9uUGIOJ/+40RnoR56WW9gp3LFIu5KrZ0NfHu98LuyaIVzFJ7X/c/YJPzqHyTWIq4prwS6LX3+xqV03R5EhU6tTYXH84CnXMXFvzTJqouq9EI+nC4RdRSAiQ+qqHG8V6ZARKCgtawzUd98pPhryJ8paaya/TAzIns68dbH4XN4dcyf1VXqEMyJHU+yJb6BpaUJFVg5DFE5oSQeKd69luFbBWFiJEWLYLp9Vf/gNcPL7WcI5gbqCDRX+BusH8HPN9J6chOMxBhsksIrC41BsMDoXh8vqG5JLg63FgDgpowJ19LTWNPeOAv4TtCKd9UWXUpyhF6CJbq07Qp9F7sF7ql+8qzUUD79CDOhCVFkYVBR0FilSY2Pob5xAdm1N2BjGG1Co9vMr8W/0L+xff3I5Djv8y9aWudTH/fl9Dd3fwrnqOjH8Y94ZnBC0qxMZlqWT5NekVNzLczIFVgujydEHd3Rw99e3S3q/1AN7xk6Q+HR6r1RxpcfE4HpppJC1FMDl5VY13fFxrOtQOoRpmZZzfHCfnZqnxATSIy3JMdtCuxNIb8dsRNCR+ysmnq7Wm3yAuHkRvMAGKQAAPPJvtZiJLS1/piw9cDBT/h7msL1fC5R+4GaKxQ=
